### ISSUE TITLE
FindMajorityElement.py not working as expected

### ISSUE THREAD

**Issue by jmcarrillog** [MrDupin/Algorithms#1]
Hello @MrDupin 
First of all thanks for sharing some of your code, I just wanted to let you know that your script "FindMajorityElement.py" does not work as expected for some entries such as 
[1, 1, 1, 1, 1, 3, 3, 3] where the answer should be 1 but it outputs -1 as if there was not a majority element.

**Comment by antmarakis** [comment]
Hi @jmcarrillog. I am aware that the algorithm does not cover all cases, unfortunately. If the input array is in a certain form (with all the elements separated), the algorithm will not find the solution. Shuffling an array before input will usually solve this.

This was an algorithm I came up with to better understand how Divide-and-Conquer works, and to [teach its basic concepts](https://mrdupin.github.io/dnc-majority-element/).
